# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -I/home/s1143956/Analysis/LSDTopotools -I/home/s1143956/Analysis/LSDTopotools/TNT   

CXX_DEFINES = 

